### ISSUE TITLE
openwrt 19.07

### ISSUE THREAD

**Issue by czghzh** [project-openwrt/FileBrowser#5]
Failed to execute cbi dispatcher target for entry '/admin/services/filebrowser'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/filebrowser.lua:3: module 'luci.model.ipkg' not found:
	no field package.preload['luci.model.ipkg']
	no file './luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg/init.lua'
	no file '/usr/lib/lua/luci/model/ipkg.lua'
	no file '/usr/lib/lua/luci/model/ipkg/init.lua'
	no file './luci/model/ipkg.so'
	no file '/usr/lib/lua/luci/model/ipkg.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/model/cbi/filebrowser.lua:3: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:943: in function </usr/lib/lua/luci/dispatcher.lua:937>

**Comment by 1715173329** [comment]
You need to install the ipkg module  manually.
